package packer

import (
	"crypto/md5"
)

// TeeworldsNamespace is the UUID namespace used by Teeworlds/DDNet for
// computing deterministic UUIDs from message names.
// Value: e05ddaaa-c4e6-4cfb-b642-5d48e80c0029
var TeeworldsNamespace = [16]byte{
	0xe0, 0x5d, 0xda, 0xaa, 0xc4, 0xe6, 0x4c, 0xfb,
	0xb6, 0x42, 0x5d, 0x48, 0xe8, 0x0c, 0x00, 0x29,
}

// CalculateUUID computes a UUID v3 (MD5-based, RFC 4122) from the
// Teeworlds namespace and the given name string—exactly matching
// DDNet's CalculateUuid() in uuid_manager.cpp. The name is hashed
// WITHOUT a terminating NUL byte.
func CalculateUUID(name string) [16]byte {
	h := md5.New()
	h.Write(TeeworldsNamespace[:])
	h.Write([]byte(name))
	digest := h.Sum(nil)

	var uuid [16]byte
	copy(uuid[:], digest)

	// Set version 3 (UUID generated by MD5 hashing)
	uuid[6] = (uuid[6] & 0x0f) | 0x30
	// Set variant 1 (RFC 4122)
	uuid[8] = (uuid[8] & 0x3f) | 0x80

	return uuid
}
